### ISSUE TITLE
KAFKA SERVICE LIBRARY call with variable in name doesn't work

### ISSUE THREAD

**Issue by jmlecul** [cerberustesting/cerberus-core#2423] opened 2022-11-15 14:00 UTC
Cerberus Version : 4.15-1742

hi,
i have a Kafka service libray named : ARES_K001.DEV - UPDATE-PRODUCT-RESULT with UUID expected V0.3

in my step test i try to call it with a system environment variable : 
ARES_K001.%system.APP_VAR1% - UPDATE-PRODUCT-RESULT with UUID expected V0.3

Variable is resolved well but it doesn't work :
Failed to call the Service 'ARES_K001.DEV - UPDATE-PRODUCT-RESULT with UUID expected V0.3'. Caused by : Failed to search the Kafka topic 'adeo-dev-europe-west1-EVENT-SEQUOYA-REDWOOD-LM-ES-P1-C2-UPDATE-PRODUCT-RESULT-V3' from host 'pkc-7yodp.europe-west1.gcp.confluent.cloud:9092'. java.lang.NullPointerException.

For rest api it work well :
ARES_R002.%system.APP_VAR1% - UPDATE-PRODUCT with custom body RWD API V0.3
gives me a succeeded : 
'PUT' Call to Service 'ARES_R002.DEV - UPDATE-PRODUCT with custom body RWD API V0.3' to 'https://redwood-product-api-cdrpfj-dev.gke-pdp-nprd-wsaa.priv.manawa.adeo.cloud/v1/products' executed successfully and stored to memory!

thanx in advance

**Comment by vertigo17** [comment] 2022-12-28 09:41
Hello. I tested on my side and could not reproduce the issue.
If I insert a variable inside the name of the service event if it is on a kafka service it trigger the correct service with no error.

What happen if you replace 
ARES_K001.%system.APP_VAR1% - UPDATE-PRODUCT-RESULT with UUID expected V0.3
by
ARES_K001.DEV - UPDATE-PRODUCT-RESULT with UUID expected V0.3

Does it work or do you have the same error ?
I suspect the issue not to come from the variable inside the name.

Can you provide the complete stack trace of the error (from tomcat logs) ?

**Comment by vertigo17** [comment] 2023-12-27 18:44
I close the issue because no feedback was provided.

**Closed by vertigo17** 2023-12-27 18:44 UTC
Labels: Nat : bug, Status : waiting feedback, Prio : 2 normal, Perim: ENGINEActionSRVKafka, Ori : LM
