### ISSUE TITLE
Bug - Scroll doesn't work as expected since 4.16

### ISSUE THREAD

**Issue by Cyril-Bellotti** [cerberustesting/cerberus-core#2450] opened 2023-03-02 14:49 UTC
Cerberus Version : 4.16-1747

Hi, 

The action scroll doesn't work since 4.16. The action return a success result but when we check the result with a screenshot we see that the page didn't change.

How to reproduce ?
1. Add an action Scroll and define the xpath you want to scroll to
2. Add takescreenshot
3. Run the test
4. In the screenshot result we can see that the scroll has not been done

This is a very blocking point on our side.

**Comment by ittaLaRedoute** [comment] 2023-03-14 17:07
Issue also present on version 4.17

**Comment by vertigo17** [comment] 2023-04-16 20:37
duplicate of #2458

**Closed** 2023-04-16 20:37 UTC
