### ISSUE TITLE
Kafka Search vith avro schema key

### ISSUE THREAD

**Issue by jmlecul** [cerberustesting/cerberus-core#2428] opened 2022-12-01 13:39 UTC
Like the https://github.com/cerberustesting/cerberus-core/issues/2418 issue, we can read kafka topics with avro key, but : 
- The key in result is not in json format :
Obtained :  "key": "\u0000\u0000\u0001��\u001081901874\u0002\u001081901874"
Wanted : 
{
  "productReferenceBU" : "81901874",
  "productReferenceADEO" : "81901874"
}

- it is also impossible to use a filter on it ($.key)

![image](https://user-images.githubusercontent.com/114755928/205067102-b2495d7e-f877-4280-aec9-aff3ab9391ea.png)

**Comment by vertigo17** [comment] 2022-12-28 23:23
That should be fixed with #2418.
duplicate of #2418

**Closed** 2022-12-28 23:24 UTC
Labels: Nat : enhancement, Prio : 2 normal, Perim: ENGINEActionSRVKafka
