### ISSUE TITLE
ERROR - Request Entity Too Large

### ISSUE THREAD

**Issue by Kevin-Sinapayen** [cerberustesting/cerberus-core#2513] opened 2024-01-17 11:08 UTC
Cerberus Version : 4.16-1747

Hello,

Why do I have this error sometimes when I try to import a library step?
![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/dbde9fdb-48d7-42f2-93e0-4eea4eb35d99)

In this case, my library has 19 steps, is it too big?

**Comment by vertigo17** [comment] 2024-01-17 11:40
This is linked with the size of the base64 data you have inside your test.
We have on the roadmap the feature to create a file management screen that will allow to manage and upload all your files (a bit like the objects).
That way you will be allowed to manage them seperated from the testcase and point to them using %file.MYFILENAME.filename%
That will drastically reduce the size of the testcase, solving that issue.
Untill there, if possible you can try select smaller pdf to limit the issues or split your tests to different ones.

This issue is duplicate of https://github.com/cerberustesting/cerberus-core/issues/2508

**Comment by Kevin-Sinapayen** [comment] 2024-01-17 14:17
OK I understand thank you!

**Comment by vertigo17** [comment] 2024-01-17 17:20
I close as duplicate of #2508

**Closed** 2024-01-17 17:20 UTC
