### ISSUE TITLE
Error in displaying test case executions history

### ISSUE THREAD

**Issue by Ouss-GL** [cerberustesting/cerberus-core#2435] opened 2022-12-15 23:30 UTC
Cerberus Version : 4.15-1742

With this Cerberus Version, by accessing to the executions history of a test case after a few moments the page will be updated and the history don't only concerns the desired test case.
Is there a solution to solve this problem temporarily while waiting for the correction of the bug.
Thank you in advance.
Best regards

**Comment by vertigo17** [comment] 2022-12-27 20:14
You can just put a value on the search field and remove it immediately. That will force the filter to apply.
BTW, this issue is a duplicate of #2419 that has been fixed for next release.

**Closed by vertigo17** 2022-12-27 20:14 UTC
