### ISSUE TITLE
[LR] Campaign modification issue

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2457] opened 2023-03-17 13:23 UTC
Hello,
 I notice that we cant no longer update campaigns header since our upgrade.
See attachment

![image](https://user-images.githubusercontent.com/97182913/225917086-72e45106-df6c-46d2-a13c-d1327b70a2f0.png)

**Comment by lucashimpens** [comment] 2023-04-26 15:01
Check with Redoute, can't reproduce the issue. Close it.

**Closed** 2023-04-26 15:02 UTC
Labels: Ori : LaRedoute
