### ISSUE TITLE
[Cerberus 4.13][Bug blocker][User management] - 404 Not Found

### ISSUE THREAD

**Issue by CLion59** [cerberustesting/cerberus-core#2296] opened 2021-09-14 08:21 UTC
**Description**

On Cerberus 4.13, when I click on "Manage user", I'm redirected on 404 page.

**Comment by vertigo17** [comment] 2021-09-15 14:06
Hello,
4.13 is not released yet.
Can you report the full version ? Is that Cerberus4.13-SNAPSHOT-1640 Build 20210910-132304 ?
What URL is redirected ? (the one that produce the 404)
Are you using Keycloak ?

**Comment by vertigo17** [comment] 2022-08-19 11:26
I close the issue as I could not reproduce. Don’t hesitate to reopen or create a new one with the details if necessary.

**Closed by vertigo17** 2022-08-19 11:26 UTC
Labels: Status : waiting feedback, Perim : OTHERS, Prio : 2 normal, Nat : question
