### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by Cyril-Bellotti** [cerberustesting/cerberus-core#2424] opened 2022-11-25 08:55 UTC
Cerberus Version : 4.15-1742

Hi, 

There is a problem on the test case execution page with the filters.

The problem was discovered by going through the "Execution List" button from a test case script, but it is reproducible by hand as explained below:

The test was done by selecting 2 filters:
- If you select a first filter (ex : Test Folder) then select a second one (ex: Testcase ID), the filter on the list is done correctly. What we see is that the url of cerberus has changed and displays the selected filter. Ex : https://my-cerberus-url.com/TestCaseExecutionList.jsp?Test=%20LM%20-%20CCDP%20-%20Autonomous%20Checkout&TestCase=0001A
- If we refresh the page, the first 5 seconds the filters are correctly applied, then an automatic refresh is done removing the filters from the list. They are still visible and selected, but the list is not filtered.

Here is 2 videos showing the problem. When we see that the page is refreshed, no action on our part has been taken

https://user-images.githubusercontent.com/60349932/203940439-6d34bd3b-31a5-484a-9eed-94349707166b.mov
https://user-images.githubusercontent.com/60349932/203940410-d5f19934-68cb-4f6e-bf8a-c5cf820bf20d.mov

Thanks

**Comment by vertigo17** [comment] 2022-11-28 07:40
Hello Cyril.
It is a duplicate of https://github.com/cerberustesting/cerberus-core/issues/2419
That should already be fixed.
Can you confirm with latest snapshot ?

**Comment by Cyril-Bellotti** [comment] 2022-11-28 14:51
Hi @vertigo17 ,
Indeed it is fixed in the last snapshot: Cerberus4.16-SNAPSHOT-1742
Thanks

**Closed** 2022-12-07 20:51 UTC
Labels: Nat : bug, Perim : GUIExecution, Prio : 2 normal
