### ISSUE TITLE
[Cerberus Version : 4.16-1747][GL] The command scroll to is not working

### ISSUE THREAD

**Issue by Moujib-automate** [cerberustesting/cerberus-core#2458] opened 2023-03-22 15:42 UTC
Hello, 

we noticed that the command Scroll TO is not working ; it is performing a wait instead as shown in the screenshot

Cerberus Version : 4.16-1747
![image](https://user-images.githubusercontent.com/124173930/226958484-4806340b-e4b7-4b9a-be9f-bccb84820053.png)

**Comment by vertigo17** [comment] 2023-04-06 19:13
I will need more detail and context on that.
Can you provide the page where you want to scroll and a screenshot of the element you want to scroll to.
That could be a wrong xpath or iframe issue.
Anyway you can always try to get around that issue by scrollTo using a text or using keyPress action with page down.

**Comment by mflorid** [comment] 2023-04-13 08:52
We have the same issue here : #2450

**Comment by vertigo17** [comment] 2023-04-16 20:34
Can you put the URL that you open and the xpath in text mode so that I try to reproduce ?
Thanks.

**Comment by mflorid** [comment] 2023-04-17 08:23
> Can you put the URL that you open and the xpath in text mode so that I try to reproduce ? Thanks.

https://www.adeo.com/

xpath=(//*[@class="adeo-section fullwidth bg-darkblue padded"])[1]

or

text : À LA UNE

**Comment by vertigo17** [comment] 2023-04-23 14:20
Issue should be fixed.
Don't hesite to reopen is not the case on latest master.

**Comment by MathisSenicourt** [comment] 2024-04-16 14:41
Hi, the issue seems to be still present on 4.18

**Comment by MathisSenicourt** [comment] 2024-04-18 13:02
The scroll doesn't work but there is no error from cerberus. To reproduce :

open url :
https://www.laredoute.it/ppdp/prod-350309180.aspx

reject cookies by cliking on:
//*[@id="popin_tc_privacy_button_2"]

scroll to :
//button[contains(@class,'product-rating-open-language')]//span


there is a bypass by using javascrip :

document.evaluate("XPATH HERE", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.scrollIntoView();

and example: document.evaluate("//*[@data-cerberus='color']", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.scrollIntoView();

**Comment by vertigo17** [comment] 2024-04-19 18:25
fixed with commit https://github.com/cerberustesting/cerberus-core/commit/9757314baa56a5838d0bd830151027b319f980fb

**Closed by vertigo17** 2024-04-19 18:25 UTC
Labels: Nat : bug, Perim : ENGINEActionWeb, Prio : 1 high+
